---

- name: Install sentry package dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  register: install_sentry_package_dependencies
  when: _sentry_package_dependencies is defined
  with_items: "{{ _sentry_package_dependencies | default([]) }}"
  tags:
    - package
    - dependencies
- debug: var=install_sentry_package_dependencies.stdout_lines

- name: Install sentry dependencies
  become: true
  package:
    name: "{{ item.name }}"
    state: present
  register: install_sentry_dependencies
  when: _sentry_dependencies is defined
  with_items: "{{ _sentry_dependencies | default({}) }}"
  tags:
    - package
    - dependencies
- debug: var=install_sentry_dependencies.stdout_lines
